---
language: rust
rust: nightly

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo clippy
  - cargo build --verbose --all
  - cargo test --verbose --all
