---
language: rust
rust: nightly
env:
  - SH=bash

before_script:
  - sudo add-apt-repository -y ppa:duggan/bats
  - sudo apt-get update
  - sudo apt-get install bats
  - rustup component add rustfmt

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo install --path .
  - bats e2e/*
