# define your branches prefixes
id = 1
name = "test"
branch_types = ["fix", "feat", "chore", "style", "doc"]
commit_types = ["fix", "feat", "chore", "style", "doc"]
# branch prefix separator : `feat/some-feature`
branch_separator = "/"
# jira user name of your default reviewers
reviewers = ["john doe", "michel dupont", "alice white"]
# user to assign your completed issues
default_assignee =  "kevin the techlead"